#!/bin/bash
service tor start
IP=$(torify 2> /dev/null wget 216.146.38.70:80 -O - -o /dev/null | cut -d" " -f6 | sed 's/<\/body><\/html>//') 
sleep 1
echo "TOR IP ${IP}"



while :
do

 hour=0
 min=2
 sec=0

        while [ $hour -ge 0 ]; do
                 while [ $min -ge 0 ]; do
                         while [ $sec -ge 0 ]; do
                                 echo -ne "$hour:$min:$sec\033[0K\r"
                                 let "sec=sec-1"
                                 sleep 1
                         done
                         sec=59
                         let "min=min-1"
                 done
                 min=59
                 let "hour=hour-1"
	done

	service tor stop
	service tor start
	sleep 1
	ip=$(torify 2> /dev/null wget 216.146.38.70:80 -O - -o /dev/null | cut -d" " -f6 | sed 's/<\/body><\/html>//') 
	echo "TOR RESTARTED ${ip}"
	
done
